apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-single
spec:
  serviceName: "pg-single"
  replicas: 1
  selector:
    matchLabels:
      app: pg-single
  template:
    metadata:
      labels:
        app: pg-single
    spec:
      containers:
      - name: pg-db-pod
        image: postgres:latest
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: pg-single-configmap
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: pg-single-configmap
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-single-secret
                key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          name: pgport
        volumeMounts:
        - name: pgclaim
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: pgclaim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: managed-premium
      resources:
        requests:
          storage: 1Gi